
services:
  db:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 300s
      retries: 5
    volumes:
      - './wideworldimports/snapshots/wwi-dump:/wwi/dump'
    restart: always
    ports:
      - "5438:5432"